package id.my.anciety.malink.security.malink

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.put
import org.junit.Assert.assertEquals
import org.junit.Assert.assertThrows
import org.junit.Test

/** Static fixture generated by packages/security, never by the Kotlin implementation. */
class CrossLanguageFixtureTest {
    private val root = Json.parseToJsonElement(FIXTURE).jsonObject
    private val offer = PairingCodec.parseOffer(root.getValue("offer").jsonObject)
    private val request = PairingCodec.parseRequest(root.getValue("request").jsonObject)
    private val response = PairingCodec.parseResponse(root.getValue("response").jsonObject)

    @Test
    fun `verifies TypeScript pairing offer request response and certificate`() {
        assertEquals("gateway-1", PairingSecurity.verifyOffer(offer, offer.offer.gatewayKey, NOW).gatewayId)
        assertEquals("phone-1", PairingSecurity.verifyRequest(request, offer, NOW).deviceId)
        assertEquals(
            "certificate-cross-1",
            PairingSecurity.verifyResponse(
                response,
                offer,
                request,
                offer.offer.gatewayKey,
                NOW + 3,
            ).certificate.certificate.certificateId,
        )
    }

    @Test
    fun `opens TypeScript secure envelope with injected JVM recipient identity`() {
        val gateway = TestP256Identity.fromPrivateJwk(
            EcPublicJwk(GATEWAY_X, GATEWAY_Y),
            GATEWAY_D,
        )
        val signed = SecureEnvelopeCodec.parse(CanonicalJson.encode(root.getValue("envelope")))
        val opened = SecureEnvelopes.openSecureEnvelope(
            signed,
            gateway,
            request.request.deviceKey,
            SecureEnvelopeBindings(
                gatewayId = "gateway-1",
                conversationId = "conversation-1",
                direction = SecureEnvelopeDirection.DEVICE_TO_GATEWAY,
                senderDeviceId = "phone-1",
                recipientDeviceId = "gateway-device",
                senderKeyId = request.request.deviceKey.keyId,
                recipientKeyId = offer.offer.gatewayKey.keyId,
            ),
            InMemoryReplayStore(),
            NOW + 1,
        )
        assertEquals("TypeScript encrypted fixture 😀", opened.plaintext.jsonObject.getValue("body").toString().trim('"'))
    }

    @Test
    fun `opens TypeScript Matrix timeline envelope with identical bindings`() {
        val signed = MatrixTimelineEnvelopeCodec.parse(MATRIX_TIMELINE_FIXTURE)
        val opened = MatrixTimelineEnvelopes.open(
            signed,
            Base64Url.decode(MATRIX_TIMELINE_KEY),
            offer.offer.gatewayKey,
            MatrixTimelineBindings(
                gatewayId = "gateway-1",
                conversationId = "conversation-1",
                roomId = "!private:example.org",
                epochId = "epoch-cross-1",
                sessionId = "session-cross-1",
                threadRootEventId = "${'$'}root-cross-1",
            ),
        )

        assertEquals(
            "TypeScript timeline fixture 😀",
            opened.jsonObject.getValue("body").toString().trim('"'),
        )
        assertCode(SecurityErrorCode.BINDING_MISMATCH) {
            MatrixTimelineEnvelopes.open(
                signed,
                Base64Url.decode(MATRIX_TIMELINE_KEY),
                offer.offer.gatewayKey,
                MatrixTimelineBindings(
                    gatewayId = "gateway-1",
                    conversationId = "conversation-1",
                    roomId = "!private:example.org",
                    epochId = "epoch-cross-1",
                    sessionId = "session-cross-1",
                    threadRootEventId = "${'$'}different-root",
                ),
            )
        }
    }

    @Test
    fun `opens TypeScript Matrix Room State envelope with identical bindings`() {
        val signed = MatrixStateEnvelopeCodec.parse(MATRIX_STATE_FIXTURE)
        val opened = MatrixStateEnvelopes.open(
            signed,
            Base64Url.decode(MATRIX_TIMELINE_KEY),
            offer.offer.gatewayKey,
            MatrixStateBindings(
                gatewayId = "gateway-1",
                conversationId = "conversation-1",
                roomId = "!private:example.org",
                eventType = "io.malink.session.current.v2",
                stateKey = "session-cross-1",
                epochId = "epoch-cross-1",
                stateVersion = 3,
            ),
        )

        assertEquals("session-cross-1", opened.getValue("session_id").toString().trim('"'))
        assertCode(SecurityErrorCode.BINDING_MISMATCH) {
            MatrixStateEnvelopes.open(
                signed,
                Base64Url.decode(MATRIX_TIMELINE_KEY),
                offer.offer.gatewayKey,
                MatrixStateBindings(
                    gatewayId = "gateway-1",
                    conversationId = "conversation-1",
                    roomId = "!private:example.org",
                    eventType = "io.malink.session.current.v2",
                    stateKey = "another-session",
                    epochId = "epoch-cross-1",
                    stateVersion = 3,
                ),
            )
        }
    }

    @Test
    fun `pairing rejects expiry replay bad signature and unknown fields`() {
        assertCode(SecurityErrorCode.EXPIRED) {
            PairingSecurity.verifyOffer(offer, now = offer.offer.expiresAt)
        }

        val replay = InMemoryReplayStore()
        PairingSecurity.consumeOffer(offer, request, replay, NOW)
        assertCode(SecurityErrorCode.REPLAY) {
            PairingSecurity.consumeOffer(offer, request, replay, NOW)
        }

        val signatureBytes = Base64Url.decode(offer.signature.value).also {
            it[0] = (it[0].toInt() xor 1).toByte()
        }
        assertCode(SecurityErrorCode.INVALID_SIGNATURE) {
            PairingSecurity.verifyOffer(
                offer.copy(signature = offer.signature.copy(value = Base64Url.encode(signatureBytes))),
                now = NOW,
            )
        }

        val offerJson = CanonicalJson.encode(offer.toJson())
            .replaceFirst("\"offer\":{", "\"offer\":{\"unknown\":true,")
        assertThrows(IllegalArgumentException::class.java) { PairingCodec.parseOffer(offerJson) }
    }

    @Test
    fun `Gateway trust codec persists transport cursor and rejects pre-release schema`() {
        val base = GatewayTrust(offer, request, response)
        val rotatedTransport = base.certificate.gatewayTransport.copy(
            deviceId = "GATEWAY2",
            ed25519 = "gateway-ed25519-fingerprint-2",
        )
        val rotated = base.copy(
            transportTrust = base.transportTrust.copy(
                currentTransport = rotatedTransport,
                lastIssuedAt = NOW + 10,
            ),
        )
        val restored = GatewayTrustCodec.decode(GatewayTrustCodec.encode(rotated))
        assertEquals(rotatedTransport, restored.transportTrust.currentTransport)
        assertEquals(NOW + 10, restored.transportTrust.lastIssuedAt)

        val legacy = CanonicalJson.bytes(buildJsonObject {
            put("schemaVersion", 1)
            put("offer", offer.toJson())
            put("request", request.toJson())
            put("response", response.toJson())
        })
        assertThrows(IllegalArgumentException::class.java) {
            GatewayTrustCodec.decode(legacy)
        }
    }

    @Test
    fun `pairing rejection must be Gateway signed and request bound`() {
        val gateway = TestP256Identity.fromPrivateJwk(
            EcPublicJwk(GATEWAY_X, GATEWAY_Y),
            GATEWAY_D,
        )
        val rejection = PairingRejection(
            offerId = offer.offer.offerId,
            requestId = request.request.requestId,
            requestDigest = PairingSecurity.requestDigest(request),
            gatewayId = offer.offer.gatewayId,
            code = PairingRejectionCode.GATEWAY_REJECTED,
            message = "Pairing was declined.",
            retryable = false,
            issuedAt = NOW + 3,
            expiresAt = NOW + 60_000,
        )
        val preimage = CanonicalJson.bytes(buildJsonObject {
            put("domain", "malink.pairing.rejection.v1")
            put("document", rejection.toJson())
        })
        val signed = SignedPairingRejection(
            rejection,
            PairingSignature(gateway.publicIdentity.keyId, Base64Url.encode(gateway.sign(preimage))),
        )
        assertEquals(
            PairingRejectionCode.GATEWAY_REJECTED,
            PairingSecurity.verifyRejection(signed, offer, request, NOW + 4).code,
        )
        assertCode(SecurityErrorCode.BINDING_MISMATCH) {
            PairingSecurity.verifyRejection(
                signed.copy(rejection = rejection.copy(requestId = "different-request")),
                offer,
                request,
                NOW + 4,
            )
        }
    }

    private fun assertCode(code: SecurityErrorCode, block: () -> Unit) {
        val error = assertThrows(MalinkSecurityException::class.java, block)
        assertEquals(code, error.code)
    }

    private companion object {
        const val NOW = 1_800_000_000_000L
        const val GATEWAY_X = "1siSvHSRoOQTkfn_uzHGRR7mlrF14hRSidQrrkSjQ7w"
        const val GATEWAY_Y = "JLwmVQAUZvm_JOBQI6wBY_h7sNz5TuA2ICpclQk3twA"
        const val GATEWAY_D = "IsKgdASANPgY8A1pTLjxZ2-pJDPesTHsyRZuK2UEsIg"
        const val MATRIX_TIMELINE_KEY = "AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8"
        val MATRIX_TIMELINE_FIXTURE = """
{"envelope":{"kind":"malink.matrix-timeline-envelope","version":2,"envelopeId":"timeline-envelope-cross-1","contentType":"io.malink.matrix-timeline-content.v2","gatewayId":"gateway-1","conversationId":"conversation-1","roomId":"!private:example.org","epochId":"epoch-cross-1","logicalEventId":"logical-cross-1","sessionId":"session-cross-1","threadRootEventId":"__DOLLAR__root-cross-1","issuedAt":1800000000000,"nonce":"sInPPoYbf2hM1Q7o","ciphertext":"gBIbL_BdBqioaLqPSuIRB1R0Hv1IXcthr-_L8AuYxfRKla7XeHrv3j7ZVFasvGc-jbQhEXsjgJB_ZiY"},"signature":{"algorithm":"ES256","keyId":"MsGTFCvsPKYo6KybfH4t9cOai5kX99MDFyG5fJ4cs94","value":"zE0AJukVXjd4AG6_eCI4EuFdoK6FLjj5CT4u7v9v3IzCao9wtnx50kl0PtfKK8zLjMMEKCNH_0PkZ0Z8nOzsxQ"}}
""".trimIndent().replace("__DOLLAR__", "\$")
        val MATRIX_STATE_FIXTURE = """
{"envelope":{"kind":"malink.matrix-state-envelope","version":2,"contentType":"io.malink.matrix-state-content.v2","gatewayId":"gateway-1","conversationId":"conversation-1","roomId":"!private:example.org","eventType":"io.malink.session.current.v2","stateKey":"session-cross-1","epochId":"epoch-cross-1","stateVersion":3,"issuedAt":1800000000000,"nonce":"gpFuTjjoMVJU3XeM","ciphertext":"Vxe1RUE7f4i6TQ5A14CJsZm6J-dAIaSmN5rzY7HsqyfLyN8Tg6nlgYSsC1r5cH3anSpgzC-qL9rUgay1vyJVDcdkJ705UpSIUjs39NX4h3KEfYIdcf92BLg7eKLMFUIUrxkqlD0asxA3rpmG_2BnAeLflQyjBSSLJmZYrC1ZQKa-jGZ7oSfHNeVdjsMOamvYj8WRgFAO_2HxspQ3tFdWWWf8kCzA3QVdLuyn93Hjmbx2GaDJXdKKAI2IHMOXgFoGeh5riXay2AQPmP_g3xkBjW4lAv9oHb_CHRYG2VF7mcLk4ZAQvxskSj2sRSQaVz7HZaabEqJwVe5D7OvtNGs5YKCjbgXaUIbxMlh8rk0KcQ8-lOzTWPmS-IOxxl5JPlNS_GJNtVH6vNEvDtE_H3552JzDU7wj-pMET1Sxvy3_7pEcrOXtDggT_3P4iqXG0WHJpeRbB4JOKLewU9vU_Zq0_BReReOkZ3Jd-Tuq02SCTBULQDrps1ytCe9h-ztrNbG76qAb6SeE8clKNSJM-wFg0vpRPVk7RFr28qvNl_WpEdjPaHuOco3OSp1IYt-JfvJfPSocaWhXmWQOwMJoAd8pcX6RFrLPrZc5o2UWrCQmxdl_ayHvA52e_wg14xRCvbHzdk21mDPLjpdfcERC87f8SCQ4eU9UFi0ccxH3yEJaJsP1G7wQ1KzhiVd3cBpaHP7_whgg0sLFoAtXUTqzKr8w_LPtQpiL2lNI_rPUeN1_meFB91kyrQ"},"signature":{"algorithm":"ES256","keyId":"MsGTFCvsPKYo6KybfH4t9cOai5kX99MDFyG5fJ4cs94","value":"KwYKcRmOteIK6EzupxUR2c91E56SOTCOjyMb_9F4xCR4wV5dWHD8ZGxIenbz7cHcraVO2Exb4ojAzMRWvOYHYg"}}
""".trimIndent()
        val FIXTURE = """
{"offer":{"offer":{"kind":"malink.pairing.offer","version":1,"offerId":"offer-cross-1","gatewayId":"gateway-1","gatewayName":"Cross fixture 😀","gatewayKey":{"version":1,"algorithm":"ES256","keyId":"MsGTFCvsPKYo6KybfH4t9cOai5kX99MDFyG5fJ4cs94","publicKey":{"kty":"EC","crv":"P-256","x":"1siSvHSRoOQTkfn_uzHGRR7mlrF14hRSidQrrkSjQ7w","y":"JLwmVQAUZvm_JOBQI6wBY_h7sNz5TuA2ICpclQk3twA","ext":true,"key_ops":["verify"]}},"gatewayTransport":{"homeserver":"https://matrix.example.org","roomId":"!private:example.org","userId":"@gateway:example.org","deviceId":"GATEWAY1","ed25519":"gateway-ed25519-fingerprint"},"challenge":"QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ","allowedOperations":["prompt","cancel"],"issuedAt":1799999999000,"expiresAt":1800000060000},"signature":{"algorithm":"ES256","keyId":"MsGTFCvsPKYo6KybfH4t9cOai5kX99MDFyG5fJ4cs94","value":"w3yMAStYjHL5USH3_0OAxGtzvdIq5AIoxLeWJUQJZ9mSMzPibWVxRvKSsjMarxQIr1UnkMHFQ9OTNJyAmPU3gQ"}},"request":{"request":{"kind":"malink.pairing.request","version":1,"requestId":"request-cross-1","offerId":"offer-cross-1","offerDigest":"326BkqFQ5Fg6Yx5tnhb9_iuVyo3CxHgXUVSYccAXNhI","gatewayId":"gateway-1","deviceId":"phone-1","deviceName":"Fixture phone","deviceKey":{"version":1,"algorithm":"ES256","keyId":"J_PDuSugAh-4hs6DSuX4EJHEUnjm3SvFKq9RGDnidnU","publicKey":{"kty":"EC","crv":"P-256","x":"wkUM19ZRn_SiBIR21pOR0OXLjkmOhVYemHdSJRllBYE","y":"neFNM7xB5fb7DZIpp_7_9sLZPtQ9Z4cgjVo2b1t406s","ext":true,"key_ops":["verify"]}},"deviceTransport":{"homeserver":"https://matrix.example.org","roomId":"!private:example.org","userId":"@alice:example.org","deviceId":"PHONE1","ed25519":"phone-ed25519-fingerprint"},"requestedOperations":["prompt"],"issuedAt":1800000000000,"expiresAt":1800000030000},"signature":{"algorithm":"ES256","keyId":"J_PDuSugAh-4hs6DSuX4EJHEUnjm3SvFKq9RGDnidnU","value":"iiWN6tugN1adlDvLLZd1g_uUxbl2cYIDZVmBfq2Yl9a1CUKFvVy1J8mceELwpNwS26XHuxl_tp0OFwHl1cOicQ"}},"response":{"response":{"kind":"malink.pairing.response","version":1,"offerId":"offer-cross-1","requestId":"request-cross-1","requestDigest":"-NGlMZqECZ78IfdfGnpwGp_ABFdfU9zpy2iWfitr0Oo","gatewayId":"gateway-1","activeDeviceCount":2,"certificate":{"certificate":{"kind":"malink.pairing.certificate","version":1,"certificateId":"certificate-cross-1","offerId":"offer-cross-1","offerDigest":"326BkqFQ5Fg6Yx5tnhb9_iuVyo3CxHgXUVSYccAXNhI","requestId":"request-cross-1","requestDigest":"-NGlMZqECZ78IfdfGnpwGp_ABFdfU9zpy2iWfitr0Oo","gatewayId":"gateway-1","gatewayKeyId":"MsGTFCvsPKYo6KybfH4t9cOai5kX99MDFyG5fJ4cs94","gatewayTransport":{"homeserver":"https://matrix.example.org","roomId":"!private:example.org","userId":"@gateway:example.org","deviceId":"GATEWAY1","ed25519":"gateway-ed25519-fingerprint"},"deviceId":"phone-1","deviceName":"Fixture phone","deviceKey":{"version":1,"algorithm":"ES256","keyId":"J_PDuSugAh-4hs6DSuX4EJHEUnjm3SvFKq9RGDnidnU","publicKey":{"kty":"EC","crv":"P-256","x":"wkUM19ZRn_SiBIR21pOR0OXLjkmOhVYemHdSJRllBYE","y":"neFNM7xB5fb7DZIpp_7_9sLZPtQ9Z4cgjVo2b1t406s","ext":true,"key_ops":["verify"]}},"deviceTransport":{"homeserver":"https://matrix.example.org","roomId":"!private:example.org","userId":"@alice:example.org","deviceId":"PHONE1","ed25519":"phone-ed25519-fingerprint"},"allowedOperations":["prompt"],"issuedAt":1800000000001,"expiresAt":1800086400000},"signature":{"algorithm":"ES256","keyId":"MsGTFCvsPKYo6KybfH4t9cOai5kX99MDFyG5fJ4cs94","value":"8cJEsSpOkIBbQ45pCyMfnkt5-5hw4ydoDAnnPTUTeK6BBeliBwWi0Qu-UBC50wq1FwrmdCYuzmUtIDgtiAZutg"}},"issuedAt":1800000000002,"expiresAt":1800000090000},"signature":{"algorithm":"ES256","keyId":"MsGTFCvsPKYo6KybfH4t9cOai5kX99MDFyG5fJ4cs94","value":"IBufj-ooQcIiS3Wap_OJbRjtoDozlGbzG56086hcojrYezxf6qZGGQFVbgEnqJ5mcZoaiUeniw3Psj3j3y7qWg"}},"envelope":{"envelope":{"kind":"malink.secure-envelope","version":1,"envelopeId":"envelope-cross-1","contentType":"io.malink.matrix-content.v1","gatewayId":"gateway-1","conversationId":"conversation-1","direction":"device_to_gateway","senderDeviceId":"phone-1","recipientDeviceId":"gateway-device","senderKeyId":"J_PDuSugAh-4hs6DSuX4EJHEUnjm3SvFKq9RGDnidnU","recipientKeyId":"MsGTFCvsPKYo6KybfH4t9cOai5kX99MDFyG5fJ4cs94","issuedAt":1800000000000,"expiresAt":1800000120000,"nonce":"Y0b1-5dm_X9t9Qr4","ciphertext":"6sIcRJGMwC-iKT6E6RNT2CmMn5I3okrOSV9SuuIRPxVkTnVr6cd5gdTXg1wXNu3lZ_fukqn2FKqUviCs"},"signature":{"algorithm":"ES256","keyId":"J_PDuSugAh-4hs6DSuX4EJHEUnjm3SvFKq9RGDnidnU","value":"IRmlMhtFoxoO-XENC3nFdhjPqLj-SRW_9L1bgpIkFF7VOQeQlp_Hvjeb64kx93mqtDpzUcVoq4YXg94i6CECYA"}}}
""".trimIndent()
    }
}
