package id.my.anciety.malink.security.malink

import kotlinx.serialization.json.Json
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

class MalinkCryptoTest {
    @Test
    fun `canonical JSON matches protocol sorting escaping and number spelling`() {
        val source = Json.parseToJsonElement(
            """{"z":1.0,"a":{"y":true,"b":"line\n\u0001"},"list":[3,null],"tiny":0.000001,"huge":1e21}""",
        )
        assertEquals(
            """{"a":{"b":"line\n\u0001","y":true},"huge":1e+21,"list":[3,null],"tiny":0.000001,"z":1}""",
            CanonicalJson.encode(source),
        )
    }

    @Test
    fun `canonical JSON matches fixed TypeScript protocol fixture`() {
        val source = Json.parseToJsonElement(
            """{"emoji":"😀","control":"line\n\u0001","tiny":1e-7,"boundary":1e-6,"huge":1e21,"negativeZero":-0,"precise":333333333.33333329,"slash":"a/b","quote":"\""}""",
        )
        // Generated by packages/protocol canonicalJson, not by this implementation.
        val typescriptFixture =
            """{"boundary":0.000001,"control":"line\n\u0001","emoji":"😀","huge":1e+21,"negativeZero":0,"precise":333333333.3333333,"quote":"\"","slash":"a/b","tiny":1e-7}"""
        assertEquals(typescriptFixture, CanonicalJson.encode(source))
    }

    @Test
    fun `raw ES256 conversion verifies and rejects changed content`() {
        val identity = TestP256Identity.generate()
        val message = "protocol fixture".toByteArray()
        val signature = identity.sign(message)
        assertEquals(64, signature.size)
        assertTrue(
            MalinkCrypto.verifyRawEs256(
                MalinkCrypto.importPublicKey(identity.publicIdentity.publicKey),
                message,
                signature,
            ),
        )
        assertFalse(
            MalinkCrypto.verifyRawEs256(
                MalinkCrypto.importPublicKey(identity.publicIdentity.publicKey),
                "changed".toByteArray(),
                signature,
            ),
        )
    }
}
