import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { chromium } from 'playwright-core';
await mkdir('../../artifacts/reference-mcp', { recursive: true });
const browser = await chromium.launch({ channel: 'chrome', headless: true });
try {
 for (const viewport of [{ width: 390, height: 844 }, { width: 1280, height: 900 }]) {
  const page = await browser.newPage({ viewport }); const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  await page.goto('http://127.0.0.1:5194/malink/tests/fixtures/fork-reference-actions.html');
  await page.getByRole('button', { name: 'Create branch', exact: true }).click();
  await page.getByRole('textbox', { name: 'Branch name' }).fill('Alternative design');
  await page.getByRole('dialog').getByRole('button', { name: 'Create branch', exact: true }).click();
  await page.getByText('Created: Alternative design').waitFor();
  await page.getByRole('button', { name: 'Quote…', exact: true }).click();
  await page.getByRole('searchbox', { name: 'Search conversations' }).fill('Implementation 23');
  assert.equal(await page.getByRole('dialog').locator('svg').count() > 0, true);
  await page.screenshot({ path: `../../artifacts/reference-mcp/picker-${viewport.width}.png` });
  await page.getByRole('button', { name: /Quote in Implementation 23/ }).click();
  assert.equal(await page.getByRole('textbox', { name: 'Draft', exact: true }).inputValue(), 'My existing question');
  const answerChip = page.getByRole('button', { name: /Use a durable command journal/ });
  assert.equal(await answerChip.locator('svg').count(), 1);
  assert.equal((await answerChip.textContent())?.includes('Protocol design'), false);
  await page.screenshot({ path: `../../artifacts/reference-mcp/answer-chip-${viewport.width}.png` });
  await answerChip.click();
  await page.getByRole('heading', { name: 'Quoted answer' }).waitFor();
  assert.equal(await page.getByRole('dialog').locator('strong').first().textContent(), 'durable command journal');
  await page.screenshot({ path: `../../artifacts/reference-mcp/preview-${viewport.width}.png` });
  assert.equal(await page.getByRole('dialog').evaluate(element => { const r = element.getBoundingClientRect(); return r.left >= 0 && r.right <= innerWidth && r.bottom <= innerHeight; }), true);
  await page.evaluate(() => window.dispatchEvent(new CustomEvent('malink:native-back')));
  assert.equal(await page.getByRole('dialog').count(), 0);
  await page.getByRole('button', { name: 'Remove reference Protocol design' }).click();
  assert.equal(await answerChip.count(), 0);
  await page.getByRole('button', { name: 'Reference conversation', exact: true }).click();
  await page.getByRole('searchbox').fill('Implementation 24');
  await page.getByRole('button', { name: /Quote in Implementation 24/ }).click();
  const conversationChip = page.getByRole('button', { name: '@Protocol design', exact: true });
  assert.equal(await conversationChip.locator('svg').count(), 0);
  await conversationChip.click();
  await page.getByText(/whole saved conversation/).waitFor();
  await page.getByRole('button', { name: 'Done' }).click();
  await page.screenshot({ path: `../../artifacts/reference-mcp/draft-${viewport.width}.png` });
  await page.getByRole('button', { name: 'Share file' }).click();
  await page.getByRole('searchbox', { name: 'Search conversations' }).fill('Malink MacBook 23');
  await page.getByRole('button', { name: /Share to Implementation 23/ }).click();
  await page.getByText('Shared draft target-23').waitFor();
  await page.goto('http://127.0.0.1:5194/malink/tests/fixtures/fork-reference-actions.html?empty');
  await page.getByRole('button', { name: 'Quote…', exact: true }).click();
  await page.getByText(/No other open conversations/).waitFor();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  assert.deepEqual(errors, []); await page.close();
 }
 console.log('Shared picker, quote chips, previews, removal, whole-conversation references and native Back passed on desktop and mobile.');
} finally { await browser.close(); }
