// Run against the local Vite server: node --import tsx tests/session-project-picker.browser.mts
import assert from "node:assert/strict";
import { mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { chromium } from "playwright-core";
const artifactDirectory = fileURLToPath(new URL("../../../artifacts/", import.meta.url));
await mkdir(artifactDirectory, { recursive: true });
const browser = await chromium.launch({ channel: "chrome", headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  const url = `${process.env.PICKER_TEST_URL ?? "http://127.0.0.1:5187"}/malink/tests/fixtures/session-project-picker.html`;
  await page.goto(url);
  await page.getByRole("heading", { name: "Choose a project" }).waitFor();
  assert.equal(await page.locator("select:visible").count(), 0);
  assert.equal(await page.locator(".session-project-row:visible").count(), 45);
  const search = page.getByRole("searchbox");
  await search.fill("research linux");
  assert.equal(await page.locator(".session-project-row:visible").count(), 1);
  await page.locator(".session-project-row:visible").click();
  assert.equal(await page.getByRole("combobox", { name: "Provider", exact: true }).inputValue(), "agent");
  await page.evaluate(() => window.dispatchEvent(new CustomEvent("malink:native-back")));
  await page.getByRole("heading", { name: "Choose a project" }).waitFor();
  assert.equal(await search.inputValue(), "research linux");
  await search.fill("nothing-matches");
  await page.getByText("No projects found", { exact: true }).waitFor();
  await page.getByRole("button", { name: "Clear filters" }).click();
  await page.getByRole("button", { name: "Office Gateway · MacBook Pro", exact: true }).click();
  assert.equal(await page.locator(".session-project-row:visible").count(), 23);
  await page.getByRole("button", { name: "All devices", exact: true }).click();
  await page.locator(".session-project-results").evaluate(element => { element.scrollTop = 700; });
  const scroll = await page.locator(".session-project-results").evaluate(element => element.scrollTop);
  await page.locator(".session-project-row:visible").filter({ hasText: "Project 10" }).click();
  const selectedScroll = await page.locator(".session-project-results").evaluate(element => element.scrollTop);
  await page.getByRole("button", { name: "‹ Projects", exact: true }).click();
  assert.equal(await page.locator(".session-project-results").evaluate(element => element.scrollTop), selectedScroll || scroll);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.locator(".session-project-results").evaluate(element => { element.scrollTop = 0; });
  assert.equal(await page.locator(".session-project-footer").evaluate(element => { const rect = element.getBoundingClientRect(); return rect.left >= 0 && rect.right <= innerWidth; }), true);
  await page.screenshot({ path: `${artifactDirectory}/project-picker-mobile.png` });
  await page.setViewportSize({ width: 1280, height: 900 });
  await page.screenshot({ path: `${artifactDirectory}/project-picker-desktop.png` });
  await page.getByRole("button", { name: "Manage projects", exact: true }).click();
  await page.locator(".session-project-row").first().click();
  assert.match(await page.locator("output").innerText(), /^manage:project-/);
  await page.goto(url);
  await page.locator(".session-project-row").first().click();
  await page.evaluate(() => window.dispatchEvent(new CustomEvent("malink:native-back")));
  await page.getByRole("heading", { name: "Choose a project" }).waitFor();
  await page.evaluate(() => window.dispatchEvent(new CustomEvent("malink:native-back")));
  assert.equal(await page.getByRole("dialog").count(), 0);
  await page.goto(`${url}?project-entry`);
  await page.getByRole("heading", { name: "Create a session" }).waitFor();
  await page.getByRole("button", { name: /Change ›/ }).click();
  await page.getByRole("heading", { name: "Choose a project" }).waitFor();
  await page.evaluate(() => window.dispatchEvent(new CustomEvent("malink:native-back")));
  await page.getByRole("heading", { name: "Create a session" }).waitFor();
  await page.getByRole("button", { name: "Create session", exact: true }).click();
  assert.equal(JSON.parse(await page.locator("output").innerText()).projectId, "project-0");
  assert.deepEqual(errors, []);
  console.log("Project picker browser checks passed: search, filters, duplicate names, defaults, native Back, scroll, management, project entry, submission, mobile and desktop layout.");
} finally { await browser.close(); }
